CREATE TABLE IF NOT EXISTS chapters (
    id UUID PRIMARY KEY,
    course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    sequence_order INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE lessons ADD COLUMN IF NOT EXISTS chapter_id UUID REFERENCES chapters(id) ON DELETE CASCADE;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS lesson_type VARCHAR(50) DEFAULT 'VIDEO';
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS content_url TEXT;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS video_thumbnail_url TEXT;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS quiz_data TEXT;
