CREATE TABLE IF NOT EXISTS media (
    id UUID PRIMARY KEY,
    original_filename VARCHAR(255) NOT NULL,
    object_key VARCHAR(500) NOT NULL,
    media_type VARCHAR(50) NOT NULL,
    mime_type VARCHAR(100),
    file_size BIGINT,
    status VARCHAR(50) NOT NULL DEFAULT 'UPLOADING',
    uploaded_by UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
