global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'learning-platform-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend-app:8080', 'host.docker.internal:8080']
